name: Deploy to Production

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: deploy-production-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-push:
    uses: ./.github/workflows/.reusable-build-push-ecr.yml
    with:
      environment: production
    secrets: inherit
