name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-staging
  cancel-in-progress: true

jobs:
  build-push:
    uses: ./.github/workflows/.reusable-build-push-ecr.yml
    with:
      environment: staging
    secrets: inherit
